// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoReq) Reset()         { *m = InfoReq{} }
func (m *InfoReq) String() string { return proto.CompactTextString(m) }
func (*InfoReq) ProtoMessage()    {}
func (*InfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *InfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoReq.Unmarshal(m, b)
}
func (m *InfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoReq.Marshal(b, m, deterministic)
}
func (m *InfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoReq.Merge(m, src)
}
func (m *InfoReq) XXX_Size() int {
	return xxx_messageInfo_InfoReq.Size(m)
}
func (m *InfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoReq proto.InternalMessageInfo

type InfoRes struct {
	PublicKey            string                `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Host                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	HostVpnIp            string                `protobuf:"bytes,4,opt,name=host_vpn_ip,json=hostVpnIp,proto3" json:"host_vpn_ip,omitempty"`
	MetadataEnabled      bool                  `protobuf:"varint,5,opt,name=metadata_enabled,json=metadataEnabled,proto3" json:"metadata_enabled,omitempty"`
	IsAdmin              bool                  `protobuf:"varint,6,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	AllowedIps           string                `protobuf:"bytes,7,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	DnsEnabled           bool                  `protobuf:"varint,8,opt,name=dns_enabled,json=dnsEnabled,proto3" json:"dns_enabled,omitempty"`
	DnsAddress           string                `protobuf:"bytes,9,opt,name=dns_address,json=dnsAddress,proto3" json:"dns_address,omitempty"`
	DnsUpstream          []string              `protobuf:"bytes,10,rep,name=dns_upstream,json=dnsUpstream,proto3" json:"dns_upstream,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *InfoRes) Reset()         { *m = InfoRes{} }
func (m *InfoRes) String() string { return proto.CompactTextString(m) }
func (*InfoRes) ProtoMessage()    {}
func (*InfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *InfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRes.Unmarshal(m, b)
}
func (m *InfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRes.Marshal(b, m, deterministic)
}
func (m *InfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRes.Merge(m, src)
}
func (m *InfoRes) XXX_Size() int {
	return xxx_messageInfo_InfoRes.Size(m)
}
func (m *InfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRes proto.InternalMessageInfo

func (m *InfoRes) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *InfoRes) GetHost() *wrappers.StringValue {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *InfoRes) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *InfoRes) GetHostVpnIp() string {
	if m != nil {
		return m.HostVpnIp
	}
	return ""
}

func (m *InfoRes) GetMetadataEnabled() bool {
	if m != nil {
		return m.MetadataEnabled
	}
	return false
}

func (m *InfoRes) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *InfoRes) GetAllowedIps() string {
	if m != nil {
		return m.AllowedIps
	}
	return ""
}

func (m *InfoRes) GetDnsEnabled() bool {
	if m != nil {
		return m.DnsEnabled
	}
	return false
}

func (m *InfoRes) GetDnsAddress() string {
	if m != nil {
		return m.DnsAddress
	}
	return ""
}

func (m *InfoRes) GetDnsUpstream() []string {
	if m != nil {
		return m.DnsUpstream
	}
	return nil
}

func init() {
	proto.RegisterType((*InfoReq)(nil), "proto.InfoReq")
	proto.RegisterType((*InfoRes)(nil), "proto.InfoRes")
}

func init() {
	proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7)
}

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x4e, 0xeb, 0x30,
	0x10, 0x46, 0x6f, 0xda, 0xf4, 0x27, 0xd3, 0xea, 0x82, 0xbc, 0x32, 0x15, 0x94, 0xd0, 0x55, 0xd8,
	0xa4, 0xa8, 0x3c, 0x41, 0x17, 0x2c, 0x2a, 0x76, 0xa9, 0xe8, 0x36, 0x72, 0xb0, 0x5b, 0x22, 0x52,
	0xdb, 0x78, 0x92, 0x56, 0x7d, 0x55, 0x9e, 0x06, 0xd9, 0x4e, 0x90, 0x58, 0x65, 0xe6, 0xe4, 0xcc,
	0x7c, 0xd2, 0x18, 0xa6, 0x28, 0xcc, 0x49, 0x98, 0x54, 0x1b, 0x55, 0x2b, 0x32, 0x70, 0x9f, 0xd9,
	0xfc, 0xa0, 0xd4, 0xa1, 0x12, 0x4b, 0xd7, 0x15, 0xcd, 0x7e, 0x79, 0x36, 0x4c, 0x6b, 0x61, 0xd0,
	0x6b, 0x8b, 0x08, 0x46, 0x1b, 0xb9, 0x57, 0x99, 0xf8, 0x5a, 0x7c, 0xf7, 0xba, 0x1a, 0xc9, 0x1d,
	0x80, 0x6e, 0x8a, 0xaa, 0x7c, 0xcf, 0x3f, 0xc5, 0x85, 0x06, 0x71, 0x90, 0x44, 0x59, 0xe4, 0xc9,
	0xab, 0xb8, 0x90, 0x27, 0x08, 0x3f, 0x14, 0xd6, 0xb4, 0x17, 0x07, 0xc9, 0x64, 0x75, 0x9b, 0xfa,
	0x90, 0xb4, 0x0b, 0x49, 0xb7, 0xb5, 0x29, 0xe5, 0x61, 0xc7, 0xaa, 0x46, 0x64, 0xce, 0x24, 0x04,
	0x42, 0xad, 0x4c, 0x4d, 0xfb, 0x71, 0x90, 0x0c, 0x32, 0x57, 0x93, 0x39, 0x4c, 0xec, 0xbf, 0xfc,
	0xa4, 0x65, 0x5e, 0x6a, 0x1a, 0xfa, 0x14, 0x8b, 0x76, 0x5a, 0x6e, 0x34, 0x79, 0x84, 0xeb, 0xa3,
	0xa8, 0x19, 0x67, 0x35, 0xcb, 0x85, 0x64, 0x45, 0x25, 0x38, 0x1d, 0xc4, 0x41, 0x32, 0xce, 0xae,
	0x3a, 0xfe, 0xe2, 0x31, 0xb9, 0x81, 0x71, 0x89, 0x39, 0xe3, 0xc7, 0x52, 0xd2, 0xa1, 0x53, 0x46,
	0x25, 0xae, 0x6d, 0x4b, 0xee, 0x61, 0xc2, 0xaa, 0x4a, 0x9d, 0x05, 0xcf, 0x4b, 0x8d, 0x74, 0xe4,
	0x52, 0xa0, 0x45, 0x1b, 0x8d, 0x56, 0xe0, 0x12, 0x7f, 0x13, 0xc6, 0x6e, 0x1c, 0xb8, 0xc4, 0x6e,
	0x79, 0x2b, 0x30, 0xce, 0x8d, 0x40, 0xa4, 0x91, 0xdf, 0xc0, 0x25, 0xae, 0x3d, 0x21, 0x0f, 0x30,
	0xb5, 0x42, 0xa3, 0xb1, 0x36, 0x82, 0x1d, 0x29, 0xc4, 0xfd, 0x24, 0xca, 0xec, 0xd0, 0x5b, 0x8b,
	0x56, 0x2b, 0x18, 0x6e, 0xdd, 0xf3, 0x90, 0x04, 0x42, 0x7b, 0x65, 0xf2, 0xdf, 0x9f, 0x2b, 0x6d,
	0xcf, 0x3f, 0xfb, 0xdb, 0xe3, 0xe2, 0x5f, 0x31, 0x74, 0xe0, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x83, 0x55, 0x2d, 0x1c, 0xd9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoRes, error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Info(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoRes, error) {
	out := new(InfoRes)
	err := c.cc.Invoke(ctx, "/proto.Server/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	Info(context.Context, *InfoReq) (*InfoRes, error)
}

// UnimplementedServerServer can be embedded to have forward compatible implementations.
type UnimplementedServerServer struct {
}

func (*UnimplementedServerServer) Info(ctx context.Context, req *InfoReq) (*InfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Server/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Info(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Server_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
